name: "Kumpoo Tervasulan Eliitti 2025"
description: "Badminton tournament organized by Tervasulka"

input:
  source: excel
  excel_file: "Draws Kumpoo Tervasulan Eliitti 2025 vain kaaviot.XLSX"
  web_url: "https://badmintonfinland.tournamentsoftware.com/sport/events.aspx?id=48AAE77A-2B2D-489F-863C-42A62AF6D7BD"
  full_results: false
