name: "Kumpoo Tervasulan Eliitti 2026"
description: "Badminton tournament organized by Tervasulka"

input:
  source: excel
  excel_file: "Draws Kumpoo Tervasulan Eliitti 2026.XLSX"
  web_url: "https://badmintonfinland.tournamentsoftware.com/sport/draws.aspx?id=077FA231-B428-43BA-844D-3689C1D977ED"
  full_results: false
